# Generated by Django 5.2.3 on 2025-06-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('corruption', 'Corruption'), ('criminal activity', 'Criminal  Activity'), ('drug related', 'Drug Related'), ('fraud', 'Fraud'), ('violence/threats', 'Violence/  Threats'), ('cybercrime', 'Cybercrime'), ('enviromental crime', 'Enviromental     Crime'), ('other', 'Other')], max_length=50)),
                ('urgency', models.CharField(choices=[('low - general information', 'Low - General Information'), ('medium - requires attention', 'Medium - Require Attention'), ('high - urgent action needed', 'High - Urgent Action Needed'), ('critical - immediate danger', 'Critical - Immediate Danger')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
