# Generated by Django 5.2.3 on 2025-06-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoustip',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/'),
        ),
    ]
