# Generated by Django 5.2.3 on 2025-06-30 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_anonymoustip_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoustip',
            name='access_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
