# Generated by Django 5.2.3 on 2025-07-01 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_alter_anonymoustip_access_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoustip',
            name='access_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
